# Generated by Django 4.1 on 2024-05-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Stock", "0002_stock_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock_info",
            name="stock_renew_date",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
